<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-13T17:27:40Z" name="Default suite" finished-at="2023-06-13T17:29:57Z" duration-ms="136455">
    <groups>
    </groups>
    <test started-at="2023-06-13T17:27:40Z" name="Default test" finished-at="2023-06-13T17:29:57Z" duration-ms="136455">
      <class name="com.browserstack.run_first_test.FirstTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.browserstack.run_first_test.FirstTest@73eb439a]" started-at="2023-06-13T10:27:40Z" name="setUp" finished-at="2023-06-13T10:28:20Z" duration-ms="39964" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test()[pri:0, instance:com.browserstack.run_first_test.FirstTest@73eb439a]" started-at="2023-06-13T10:28:20Z" name="test" finished-at="2023-06-13T10:29:56Z" duration-ms="95097" status="FAIL">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONArray[0] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONArray[0] not found.
	at org.json.JSONArray.get(JSONArray.java:199)
	at org.json.JSONArray.getJSONObject(JSONArray.java:362)
	at com.browserstack.run_first_test.DirectionPolyline.GetDirections(DirectionPolyline.java:64)
	at com.browserstack.run_first_test.FirstTest.performTest(FirstTest.java:191)
	at com.browserstack.run_first_test.FirstTest.test(FirstTest.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.browserstack.run_first_test.FirstTest@73eb439a]" started-at="2023-06-13T10:29:56Z" name="tearDown" finished-at="2023-06-13T10:29:57Z" duration-ms="1346" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.browserstack.run_first_test.FirstTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
